### ISSUE TITLE
New contract state: Execution engine support

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-wasm-smart-contracts#30]
**Task description**

Building on the V1 host developed in #27 the host functions dealing with state will have to be revised to use the new state implementation.

**Sub-tasks**
- [ ] Implement the new host
- [ ] Document the interface exposed to the smart contracts.
- [ ] Expose the process/init/receive functions via FFI and integrate into the node.
